### ISSUE TITLE
Create releases with download links

### ISSUE THREAD

**Issue by Neil3079** [theappbusiness/ConfigGenerator#18]
It would be useful to just download the latest version of the tool without having to clone the repository and build the code.

**Comment by ealeksandrov** [comment]
I suggest adding CI with special deployment step to automate uploading binary for released version.
Like described here: https://github.com/Carthage/Carthage/blob/master/README.md#use-travis-ci-to-upload-your-tagged-prebuild-frameworks & https://docs.travis-ci.com/user/deployment/releases/

**Comment by jsanderson44** [comment]
For the moment we have created a release with a downloadable binary. We are looking into future alternatives
