### ISSUE TITLE
configen fails when project path has spaces

### ISSUE THREAD

**Issue by KITSDavidHardiman** [theappbusiness/ConfigGenerator#19]
<img width="261" alt="screen shot 2017-06-26 at 12 56 53" src="https://user-images.githubusercontent.com/23191917/27538320-4b3b2bb4-5a6f-11e7-95b7-36ab10b1ac2b.png">

**Comment by jonhocking** [comment]
Thanks for raising this @KITSDavidHardiman. 

We typically call Configen via a shell script file and pass in environment variables. We can then include enclosing quotation marks `""` around any paths. For example:

`env=$1
"${SRCROOT}/XXX/Config/configen" -p "${SRCROOT}/XXX/Config/Config-$env.plist" -h "${SRCROOT}/XXX/Config/Config.mapping" -n Config -o "${SRCROOT}/XXX/Config/"`

Where `XXX` is the project name.

We typically call this shell script via an **External Build System** target as part of the  build chain in Xcode. You can find one of these by adding a new target to your project and looking under the *Cross Platform* tab.

Hope that helps.
Jon

**Comment by KITSDavidHardiman** [comment]
Hmm ok, @lucianomarisi FYI. We're missing quotes around the setup. One to address at some point I guess.
