### ISSUE TITLE
Unable to build the `configen.xcodeproj` project in Xcode

### ISSUE THREAD

**Issue by grifotv** [theappbusiness/ConfigGenerator#20]
Here's the error I get when building:

![4a5bufddhj](https://user-images.githubusercontent.com/435351/28063199-41a066c2-6628-11e7-80ba-148ddb927548.gif)

Am I missing something?

PS: Thanks for this great tool.

**Comment by grifotv** [comment]
#18 Sound like a good alternative.

**Comment by KaneCheshire** [comment]
Hey, @grifotv. 

Thanks for the gif, really helps! What version of Xcode are you running? Will try and look into this asap.

**Comment by grifotv** [comment]
@KaneCheshire Version 8.3.3 (8E3004b)

thanks!

**Comment by Neil3079** [comment]
I believe the tool needs to be built not run, then you take the build from your Products folder and add to your project!

**Comment by grifotv** [comment]
Thanks @Neil3079 - I'll close this issue in this case
