### ISSUE TITLE
Documentation improvement suggestions

### ISSUE THREAD

**Issue by JonCox** [theappbusiness/ConfigGenerator#24]
Ordering of instructions:
Am I right in thinking creation of the mapping & plist files should happen before generating the `configen` file? If so it's a bit confusing that the instructions seem to start with the last step.

Where does the mapping file go?
It doesn't say anywhere exactly where this mapping file should be put, and what the name of it is. All I know from the instructions is a file should be placed somewhere?

Some with the plist files. A quick sentence pointing out these files should be placed in the Configen example project before generating the `configen` file would remove any chance of confusion, perhaps pointing out the example project is available as a reference.

**Comment by jsanderson44** [comment]
HI Jon. 

The `configen` executable needs to be copied from the **`configen`** project to the target project before the mapping and plist files have any relevance. This is the **Installation** section of the documentation. The **Usage** section then details how to create the mapping and plist files before using the `configen` executable to generate the config file. 

Good point regarding the mapping and plist files - its not obvious where they should go. Typically we place them inside our project directory (in a `Config` folder for example) - not in the Configen example project. I will update this shortly. 

Let me know if you have any more questions. John

**Comment by JonCox** [comment]
Ah okay, that makes sense. Perhaps I should have read the instructions I bit more carefully ;) 

Would still be useful to detail exactly where those files go to remove any potential confusion during that part of the usage instructions.
